In [ ]:
import pandas as pd 
import re

df = pd.read_csv('shophouse_listings.csv')
df = df.drop(columns=['published','images'])
df

,product_id,title,url,price,area,toilet,location,description
0,42824448,Cực hiếm - chính chủ cho thuê shophouse TSQ Ga...,https://batdongsan.com.vn/cho-thue-shophouse-n...,180 triệu/tháng,180 m²,NaN,"Hà Đông, Hà Nội",Thông tin chi tiết: - Diện tích sử dụng cực rộ...
1,42813406,Free tới 17 tháng tiền thuê cho văn phòng và g...,https://batdongsan.com.vn/cho-thue-shophouse-n...,875 nghìn/m²,116 m²,NaN,"Ba Đình, Hà Nội",Siêu ưu đãi văn phòng & sàn thương mại hạng A ...
2,42874053,Cho thuê Shophouse lô góc mặt đường Lương Thế ...,https://batdongsan.com.vn/cho-thue-shophouse-n...,90 triệu/tháng,"139,5 m²",NaN,"Nam Từ Liêm, Hà Nội",Chủ nhà cần cho thuê căn Shophouse ML6 lô góc ...
3,42011243,Cho thuê nhà mặt phố shophouse trục chính khu ...,https://batdongsan.com.vn/cho-thue-shophouse-n...,25 triệu/tháng,80 m²,8.0,"Đan Phượng, Hà Nội",Cho thuê nhà mặt phố shophouse trục chính Khu ...
4,42868914,Cho thuê nhà 5 tầng từ 75m2-99m2-160m2-200m2 g...,https://batdongsan.com.vn/cho-thue-shophouse-n...,30 triệu/tháng,75 m²,5.0,"Hoàng Mai, Hà Nội",Shophouse 75m² từ 30tr/tháng đường nội khu. 99...
...,...,...,...,...,...,...,...,...
345,42836447,Siêu phẩm cực hiếm tại Nguyễn Văn Lộc. Địa điể...,https://batdongsan.com.vn/cho-thue-sang-nhuong...,120 triệu/tháng,·450 m²,NaN,"Hà Đông, Hà Nội",NaN
346,42836286,Cho thuê cửa hàng hiếm có tại Hàm Nghi vị trí ...,https://batdongsan.com.vn/cho-thue-sang-nhuong...,100 triệu/tháng,·500 m²,NaN,"Nam Từ Liêm, Hà Nội",NaN
347,42836417,"Cho thuê cửa hàng 90m² mặt phố Vũ Tông Phan, T...",https://batdongsan.com.vn/cho-thue-sang-nhuong...,25 triệu/tháng,·90 m²,NaN,"Thanh Xuân, Hà Nội",NaN
348,42836402,"CHO THUÊ NHÀ 80M² X 4 TẦNG PHỐ QUAN NHÂN, MT 5...",https://batdongsan.com.vn/cho-thue-sang-nhuong...,25 triệu/tháng,·80 m²,NaN,"Thanh Xuân, Hà Nội",NaN
349,42836281,"Cho thuê MBKD mặt phố Kim Ngưu, gần Times City...",https://batdongsan.com.vn/cho-thue-sang-nhuong...,18 triệu/tháng,·50 m²,NaN,"Hai Bà Trưng, Hà Nội",NaN

In [4]:
mask = df['price'].str.contains('triệu/tháng', na=False)
df_filtered = df[mask].copy()

df_filtered['area'] = df_filtered['area'].str.replace(r'[^\d.,]', '', regex=True)
df_filtered['area'] = df_filtered['area'].str.replace(',', '.', regex=False)
df_filtered['area'] = pd.to_numeric(df_filtered['area'], errors='coerce')

df_filtered

,product_id,title,url,price,area,toilet,location,description
0,42824448,Cực hiếm - chính chủ cho thuê shophouse TSQ Ga...,https://batdongsan.com.vn/cho-thue-shophouse-n...,180 triệu/tháng,180.0,NaN,"Hà Đông, Hà Nội",Thông tin chi tiết: - Diện tích sử dụng cực rộ...
2,42874053,Cho thuê Shophouse lô góc mặt đường Lương Thế ...,https://batdongsan.com.vn/cho-thue-shophouse-n...,90 triệu/tháng,139.5,NaN,"Nam Từ Liêm, Hà Nội",Chủ nhà cần cho thuê căn Shophouse ML6 lô góc ...
3,42011243,Cho thuê nhà mặt phố shophouse trục chính khu ...,https://batdongsan.com.vn/cho-thue-shophouse-n...,25 triệu/tháng,80.0,8.0,"Đan Phượng, Hà Nội",Cho thuê nhà mặt phố shophouse trục chính Khu ...
4,42868914,Cho thuê nhà 5 tầng từ 75m2-99m2-160m2-200m2 g...,https://batdongsan.com.vn/cho-thue-shophouse-n...,30 triệu/tháng,75.0,5.0,"Hoàng Mai, Hà Nội",Shophouse 75m² từ 30tr/tháng đường nội khu. 99...
5,42819911,"Cho thuê shophouse 70m2 giá cực chất 10,5 triệ...",https://batdongsan.com.vn/cho-thue-shophouse-n...,"10,5 triệu/tháng",70.0,2.0,"Gia Lâm, Hà Nội",Mở ra cơ hội cho các bạn trẻ với căn shophouse...
...,...,...,...,...,...,...,...,...
345,42836447,Siêu phẩm cực hiếm tại Nguyễn Văn Lộc. Địa điể...,https://batdongsan.com.vn/cho-thue-sang-nhuong...,120 triệu/tháng,450.0,NaN,"Hà Đông, Hà Nội",NaN
346,42836286,Cho thuê cửa hàng hiếm có tại Hàm Nghi vị trí ...,https://batdongsan.com.vn/cho-thue-sang-nhuong...,100 triệu/tháng,500.0,NaN,"Nam Từ Liêm, Hà Nội",NaN
347,42836417,"Cho thuê cửa hàng 90m² mặt phố Vũ Tông Phan, T...",https://batdongsan.com.vn/cho-thue-sang-nhuong...,25 triệu/tháng,90.0,NaN,"Thanh Xuân, Hà Nội",NaN
348,42836402,"CHO THUÊ NHÀ 80M² X 4 TẦNG PHỐ QUAN NHÂN, MT 5...",https://batdongsan.com.vn/cho-thue-sang-nhuong...,25 triệu/tháng,80.0,NaN,"Thanh Xuân, Hà Nội",NaN
349,42836281,"Cho thuê MBKD mặt phố Kim Ngưu, gần Times City...",https://batdongsan.com.vn/cho-thue-sang-nhuong...,18 triệu/tháng,50.0,NaN,"Hai Bà Trưng, Hà Nội",NaN

In [5]:
df_ocean = df_filtered[df_filtered['location'] == 'Gia Lâm, Hà Nội']
df_ocean

,product_id,title,url,price,area,toilet,location,description
5,42819911,"Cho thuê shophouse 70m2 giá cực chất 10,5 triệ...",https://batdongsan.com.vn/cho-thue-shophouse-n...,"10,5 triệu/tháng",70.0,2.0,"Gia Lâm, Hà Nội",Mở ra cơ hội cho các bạn trẻ với căn shophouse...
12,42117522,"Cho thuê shophouse nhà phố Thuận An, Trâu Quỳ ...",https://batdongsan.com.vn/cho-thue-shophouse-n...,30 triệu/tháng,90.0,NaN,"Gia Lâm, Hà Nội",NaN
21,42756074,"Cho thuê MBKD shophouse toà M3 Masteri, OCP1 đ...",https://batdongsan.com.vn/cho-thue-shophouse-n...,17 triệu/tháng,230.0,2.0,"Gia Lâm, Hà Nội",NaN
22,42756193,Cho thuê shophouse S1 - 06 OCP1 diện tích 68+6...,https://batdongsan.com.vn/cho-thue-shophouse-n...,50 triệu/tháng,130.0,1.0,"Gia Lâm, Hà Nội",NaN
23,41613365,Cho thuê shop chân đế P3 - Vinhomes Ocean Park...,https://batdongsan.com.vn/cho-thue-shophouse-n...,10 triệu/tháng,40.0,NaN,"Gia Lâm, Hà Nội",NaN
50,40118935,Chính chủ cho thuê căn shop đế mặt đường Lý Th...,https://batdongsan.com.vn/cho-thue-shophouse-n...,26 triệu/tháng,50.0,1.0,"Gia Lâm, Hà Nội",NaN
55,42755667,"Cho thuê NP mặt phố 90m2, 15 triệu/th, Thị trấ...",https://batdongsan.com.vn/cho-thue-shophouse-n...,15 triệu/tháng,90.0,NaN,"Gia Lâm, Hà Nội",NaN
73,42756191,"Cho thuê Shophouse San Hô. DT 180m2, 5T, Lô gó...",https://batdongsan.com.vn/cho-thue-shophouse-n...,18 triệu/tháng,180.0,4.0,"Gia Lâm, Hà Nội",NaN
107,42305505,Cho thuê căn shophouse diện tích lớn nhất dự á...,https://batdongsan.com.vn/cho-thue-shophouse-n...,35 triệu/tháng,103.0,5.0,"Gia Lâm, Hà Nội",NaN
108,40919214,Cho thuê shophouse 5 tầng. Đã hoàn thiện full....,https://batdongsan.com.vn/cho-thue-shophouse-n...,15 triệu/tháng,152.0,4.0,"Gia Lâm, Hà Nội",NaN
117,42806815,"Chính chủ cho thuê căn TMDV HA16 2 mặt tiền , ...",https://batdongsan.com.vn/cho-thue-shophouse-n...,30 triệu/tháng,168.0,5.0,"Gia Lâm, Hà Nội",NaN
119,42795633,"Rẻ cho thuê shop house DT 100m2 vừa ở vừa KD, ...",https://batdongsan.com.vn/cho-thue-shophouse-n...,25 triệu/tháng,100.0,NaN,"Gia Lâm, Hà Nội",NaN
143,42756191,"Cho thuê Shophouse San Hô. DT 180m2, 5T, Lô gó...",https://batdongsan.com.vn/cho-thue-shophouse-n...,18 triệu/tháng,180.0,NaN,"Gia Lâm, Hà Nội",NaN

In [14]:
url = df_ocean.values[5]
url

array([40118935,
       'Chính chủ cho thuê căn shop đế mặt đường Lý Thanh Tông MT 9,5m thích hợp làm quán cafe, siêu thị',
       'https://batdongsan.com.vn/cho-thue-shophouse-nha-pho-thuong-mai-duong-ly-thanh-tong-xa-duong-xa-prj-the-pavilion-vinhomes-ocean-park/chinh-chu-cho-can-shop-de-mat-mt-9-5m2-thich-hop-lam-quan-cafe-sieu-thi-pr40118935',
       '26 triệu/tháng', 50.0, 1.0, 'Gia Lâm, Hà Nội', nan], dtype=object)

In [15]:
df_ocean.to_csv('ocean.csv', index=False)